#What can we do with the data stored in a file?
import FormatValues as FV

#Share data between programs - each accessing the same information
#Search the file to generate marketing information
#   EX: find the most popular items ordered - Inventroy File
#   Find the customers balance EX: Customer file

#Automatic Updates - using the data to update / order
#   EX: Find out what inventory is low and order it
#   EX: find out what customers are over their limit and contact them

# Add, modify, delete records in a file

#Generate professional displays in report form - IMPORTANT

#Generate professional displays in report form.

#General procedures:
# # Text files - must be processed sequentially from the first record to the last record.
# Database tables - create an SQL statement based on what you want to do
#   This creates a new data set - and then you process the dataset from the first record.to the last record

#Code to process a text file from beginning to end.

f = open("Sales.dat", "r") #Remember the mode of "r" is to read

for SalesRecord in f: #Process each record from the first to the last
    
    #The following line reads the first record in the file and creates a list
    SalesLst = SalesRecord.split(",")
    print(SalesLst)
    
    #Now grab calues from the list and assign the variables
    #You may not need all the fields
    # strip() removes any extra characters, either before or after
    #Fields from the files are set as strings. Parse as int or float as required.
    InvNum = SalesLst[0].strip()
    EmpName = SalesLst[1].strip()
    ItemCost = float(SalesLst[2].strip())
    HST = float(SalesLst[3].strip())
    TotalCost = float(SalesLst[4].strip())
    
    #Process the data based on what is required
    print(f" {FV.FNumber0(InvNum):>2s} {EmpName:<20s} {FV.FDollar2(ItemCost):>9s} {FV.FDollar2(HST):>9s} {FV.FDollar2(TotalCost):>9s}")

f.close()
    
#Full example of a report using the customers.dat file.
#The first section of a report is the headings section.
print()
print(f"                      WIDGITS INCORPORATED")
print()
print(f"             ACCOUNTS RECEIVABLE CUSTOMER LISTING")
print()
print(f"           ACCOUNT         CUSTOMER          PHONE")
print(f"           NUMBER            NAME            NUMBER")
print(f"           ========================================")

#Initilize any required counters and accumulators.
CustCtr = 0

#The second part of the report is Details section. This is generated by processing all the records in the file.
f = open("Customers.dat", "r") #Remember the mode of "r" is to read

for CustomerRecord in f:
    CustomerLst = CustomerRecord.split(", ")
    
    AccNum = int(CustomerLst[0].strip())
    CustName = CustomerLst[1].strip()
    PhoneNum = CustomerLst[4].strip()
    
    # All required values for the detail line are availbale - no calcs
    
    print(f"           {AccNum:>5d}     {CustName:<20s}   {PhoneNum:<8s}")
    
    #Update any counters and accumulators
    CustCtr += 1
    
f.close()
#The last section of the report is the summary section. USed for Counters and Accumulators. Counters count. Accumulators total
print(f"           ========================================")
# print the counters and accumulators at the end of the report
print(f"           TOTAL CUSTOMERS LISTED: {CustCtr:>2d}")
